### ISSUE TITLE
unhandled type Address - please write a mapper for it

### ISSUE THREAD

**Issue by OscBacon** [Float-Capital/float-subgraph-uncrashable#97]
Hi, I get the following error when declaring an Address as an entityId type:
```
Generate Uncrashable Entity Helpersunhandled type Address - please write a mapper for it
```

yaml file:
```
networkConfig:
  entityIdPrefixes:
    - networks:
        - mainnet
      prefix: ""
    - networks:
        - mumbai
      prefix: mumbai
entitySettings:
  Contract:
    entityId:
      - name: addressaa
        type: Address
      - name: address
        type: Address       

```

Generated code:
```
export function generateContractId(
  addressaa: UNHANDLED_TYPE,address: UNHANDLED_TYPE
): string {
  return ENTITY_ID_PREFIX + "unhandled type in converter UNHANDLED_TYPE - Please fix the converter" + "-" + "unhandled type in converter UNHANDLED_TYPE - Please fix the converter"
}
```

What gives?
